### PR TITLE
add hotspot 1.5.1

### PR DESCRIPTION
**Pull request by Jannik2099**
This adds hotspot 1.5.1 and kddockwidgets 2.1.0

I have hardcoded both to use Qt6, we *could* technically support Qt5 / Qt6 as a user choice, but I don't think that's relevant.

I have also updated the entire md5-cache in a second commit

hotspot qcustomplot support is currently disabled due to https://github.com/KDAB/hotspot/issues/662

### CODE REVIEW

**Comment by redstrate** [comment]
Thanks for updating these! Are the gammaray/kddockwidgets ones related? I'm fine with it, but I would appreciate if they were separated into separate commits :-)

**Comment by Jannik2099** [comment]
The kddockwidgets update is related as hotspot requires a newer version that supports Qt6. I've split it into a separate commit now

As for gammaray and charmtimetracker, I only updated the repo-wide md5 cache

**Comment by xhub** [comment]
Friendly ping. Having migrating to KDE 6, it'd nice to have hotspot working in that environment as well. Thanks for your hard work!

**Comment by redstrate** [comment]
Thank you for the friendly ping! It flew under my radar once again. Thanks for updating this!

**Comment by xhub** [comment]
Thanks for the quick update! It merged fine.

**Pull request merged**
